name: ChatGPT Code Review on Push

on:
  push:
    branches:
      - main # 'main' ブランチにプッシュされた時のみトリガーされます

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # 2つ以上のコミット履歴を取得

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Send code to ChatGPT API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Install dependencies
          npm install axios

          # Fetch full history in case it's not available
          git fetch --all

          # Extract the code that was pushed and format it
          PR_CODE=$(git diff origin/main...HEAD)

          # Debugging: Check if code diff is correctly obtained
          echo "Code diff:"
          echo "$PR_CODE"

          # Check if PR_CODE is empty or not
          if [ -z "$PR_CODE" ]; then
            echo "No code changes detected."
            exit 0
          fi

          # Create the request payload with Japanese message
          REQUEST_PAYLOAD=$(cat <<EOF
          {
            "model": "gpt-4",
            "messages": [
              {"role": "system", "content": "あなたはプロフェッショナルなコードレビュアーです。"},
              {"role": "user", "content": "次のコードをレビューしてください:\n\n$PR_CODE"}
            ]
          }
          EOF
          )

          # Debugging: Check the request payload
          echo "Request payload:"
          echo "$REQUEST_PAYLOAD"

          # Send the request to ChatGPT API and capture response
          RESPONSE_CODE=$(curl -s -o response.json -w "%{http_code}" -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$REQUEST_PAYLOAD")

          # Output the response code and content
          echo "Response code: $RESPONSE_CODE"
          cat response.json | jq '.'

          if [ "$RESPONSE_CODE" -ne 200 ]; then
            echo "Failed to get a valid response from ChatGPT API"
            exit 1
          fi
